name: Minify and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        npm install terser -g
        npm install csso-cli -g
        npm install html-minifier -g
    - name: Build
      run: |
        for i in ./src/*.js; do terser $i --compress -o $i; done
        csso style.css -o style.css
        html-minifier --collapse-boolean-attributes --collapse-whitespace --minify-css --minify-js --minify-urls --remove-attribute-quotes --remove-comments --remove-empty-attributes --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-style-link-type-attributes --remove-tag-whitespace --use-short-doctype -o index.html index.html
    - name: Deploy
      run: |
        git config user.name lethiferal
        git config user.email 95504439+lethiferal@users.noreply.github.com
        git commit -am 'Automated minify of ${{ github.sha }}'
        git push --force -u origin main:gh-pages
